version: '3.8'

services:
  ci-cd-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    volumes:
      - ../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    working_dir: /workspace
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace
      - NODE_ENV=development
      - AZURE_TENANT_ID=${AZURE_TENANT_ID:-}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID:-}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    ports:
      - "8000:8000"
      - "3000:3000"
      - "5000:5000"
    networks:
      - cicd-network

  # Optional: Add a local database for testing
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=cicd_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cicd-network

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cicd-network

volumes:
  postgres_data:
  redis_data:

networks:
  cicd-network:
    driver: bridge